import type { Spot } from "@/types/spot";

export const spots: Spot[] = [
  {
    id: "spot-001",
    name: "Paws & Coffee",
    category: "cafe",
    prefecture: "東京都",
    address: "東京都渋谷区神南1-1-1",
    dogAccess: "indoor",
    supportedDogSizes: ["small", "medium"],
    hasDogRun: false,
    hasDogMenu: true,
    hasParking: false,
    websiteUrl: "https://example.com/paws-coffee",
    memo: "店内でゆっくり休める。水分補給の器が置いてある。",
    createdAt: "2026-09-01T09:00:00.000Z",
    updatedAt: "2026-09-01T09:00:00.000Z",
  },
  {
    id: "spot-002",
    name: "テラスの森",
    category: "restaurant",
    prefecture: "静岡県",
    address: "静岡県静岡市駿河区中之島2-2-2",
    dogAccess: "terrace",
    supportedDogSizes: ["small", "medium", "large"],
    hasDogRun: false,
    hasDogMenu: false,
    hasParking: true,
    websiteUrl: "https://example.com/terrace-no-mori",
    memo: "テラス席が中心。大型犬も比較的対応しやすい。",
    createdAt: "2026-09-03T12:30:00.000Z",
    updatedAt: "2026-09-03T12:30:00.000Z",
  },
  {
    id: "spot-003",
    name: "ワンダーキャンプ場",
    category: "hotel",
    prefecture: "長野県",
    address: "長野県長野市豊平区羊ヶ丘4-4-4",
    dogAccess: "indoor",
    supportedDogSizes: ["medium", "large"],
    hasDogRun: true,
    hasDogMenu: true,
    hasParking: true,
    websiteUrl: "https://example.com/wonder-camp",
    memo: "ドッグランと宿泊スペースがある。長時間滞在向き。",
    createdAt: "2026-09-05T08:00:00.000Z",
    updatedAt: "2026-09-05T08:00:00.000Z",
  },
  {
    id: "spot-004",
    name: "森の散歩公園",
    category: "attraction",
    prefecture: "山梨県",
    address: "山梨県甲府市静市町10-10",
    dogAccess: "other",
    supportedDogSizes: ["small", "medium", "large"],
    hasDogRun: true,
    hasDogMenu: false,
    hasParking: true,
    websiteUrl: "https://example.com/mori-no-sanpo",
    memo: "広い敷地でのんびり散歩できる。休憩所あり。",
    createdAt: "2026-09-07T15:00:00.000Z",
    updatedAt: "2026-09-07T15:00:00.000Z",
  },
  {
    id: "spot-005",
    name: "ドッグラン横町",
    category: "dog_run",
    prefecture: "神奈川県",
    address: "神奈川県横浜市中央区天神3-3-3",
    dogAccess: "other",
    supportedDogSizes: ["small", "medium", "large"],
    hasDogRun: true,
    hasDogMenu: true,
    hasParking: false,
    websiteUrl: "https://example.com/dog-run-yokomachi",
    memo: "大型犬も十分に遊べる広いスペース。水場がある。",
    createdAt: "2026-09-10T11:15:00.000Z",
    updatedAt: "2026-09-10T11:15:00.000Z",
  },
];
